// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to transform an image based on a text prompt.
 *
 * - animateImage - A function that handles the image transformation process.
 * - AnimateImageInput - The input type for the animateImage function.
 * - AnimateImageOutput - The return type for the animateImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnimateImageInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "The source photo to be transformed, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  prompt: z
    .string()
    .describe('The text prompt describing the desired transformation or animation style.'),
});
export type AnimateImageInput = z.infer<typeof AnimateImageInputSchema>;

const AnimateImageOutputSchema = z.object({
  dreamClipImageUri: z
    .string()
    .describe('The newly generated, transformed image as a data URI.'),
});
export type AnimateImageOutput = z.infer<typeof AnimateImageOutputSchema>;


const animateImageFlow = ai.defineFlow(
  {
    name: 'animateImageFlow',
    inputSchema: AnimateImageInputSchema,
    outputSchema: AnimateImageOutputSchema,
  },
  async ({photoDataUri, prompt}) => {
    const { media } = await ai.generate({
      model: 'googleai/gemini-2.0-flash-preview-image-generation',
      prompt: [
        { media: { url: photoDataUri } },
        { text: `Create a new image that interprets the following animation prompt: "${prompt}"` },
      ],
      config: {
        responseModalities: ['TEXT', 'IMAGE'],
      },
    });

    if (!media?.url) {
      throw new Error('Image generation failed to return an image.');
    }

    return {dreamClipImageUri: media.url};
  }
);

export async function animateImage(
  input: AnimateImageInput
): Promise<AnimateImageOutput> {
  return animateImageFlow(input);
}
