// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to stylize an image based on a text prompt.
 *
 * - styleImage - A function that handles the image stylization process.
 * - StyleImageInput - The input type for the styleImage function.
 * - StyleImageOutput - The return type for the styleImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const StyleImageInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "The source photo to be stylized, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  prompt: z.string().describe('The text prompt describing the desired artistic style.'),
});
export type StyleImageInput = z.infer<typeof StyleImageInputSchema>;

const StyleImageOutputSchema = z.object({
  stylizedImage: z.string().describe('The newly generated, stylized image as a data URI.'),
});
export type StyleImageOutput = z.infer<typeof StyleImageOutputSchema>;

export async function styleImage(input: StyleImageInput): Promise<StyleImageOutput> {
  return styleImageFlow(input);
}

const styleImageFlow = ai.defineFlow(
  {
    name: 'styleImageFlow',
    inputSchema: StyleImageInputSchema,
    outputSchema: StyleImageOutputSchema,
  },
  async ({ photoDataUri, prompt }) => {
    const { media } = await ai.generate({
      model: 'googleai/gemini-2.0-flash-preview-image-generation',
      prompt: [
        { media: { url: photoDataUri } },
        { text: prompt },
      ],
      config: {
        responseModalities: ['TEXT', 'IMAGE'],
      },
    });

    if (!media?.url) {
      throw new Error('Image generation failed to return an image.');
    }

    return { stylizedImage: media.url };
  }
);
