// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to suggest relevant hashtags based on post content.
 *
 * - suggestHashtags - A function that handles the hashtag suggestion process.
 * - SuggestHashtagsInput - The input type for the suggestHashtags function.
 * - SuggestHashtagsOutput - The return type for the suggestHashtags function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestHashtagsInputSchema = z.object({
  postContent: z.string().describe('Konten dari postingan yang akan disarankan tagarnya.'),
});
export type SuggestHashtagsInput = z.infer<typeof SuggestHashtagsInputSchema>;

const SuggestHashtagsOutputSchema = z.object({
  hashtags: z.array(z.string()).describe('Sebuah array berisi tagar yang disarankan terkait konten postingan.'),
});
export type SuggestHashtagsOutput = z.infer<typeof SuggestHashtagsOutputSchema>;

export async function suggestHashtags(input: SuggestHashtagsInput): Promise<SuggestHashtagsOutput> {
  return suggestHashtagsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestHashtagsPrompt',
  input: {schema: SuggestHashtagsInputSchema},
  output: {schema: SuggestHashtagsOutputSchema},
  prompt: `Anda adalah seorang ahli media sosial. Berdasarkan konten postingan berikut, sarankan tagar yang relevan untuk meningkatkan visibilitas.

Konten Postingan: {{{postContent}}}

Harap berikan hanya tagar, dipisahkan dengan koma.`,
});

const suggestHashtagsFlow = ai.defineFlow(
  {
    name: 'suggestHashtagsFlow',
    inputSchema: SuggestHashtagsInputSchema,
    outputSchema: SuggestHashtagsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
